# Generated by Django 4.2 on 2025-09-28 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('surname', models.CharField(max_length=100, verbose_name='Surname')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salary')),
                ('hire_date', models.DateField(verbose_name='Hire date')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.jobposition')),
            ],
        ),
    ]
