# Generated by Django 4.2 on 2025-09-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('surname', models.CharField(max_length=100, verbose_name='Surname')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('job_position', models.CharField(max_length=100, verbose_name='Job position')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salary')),
                ('hire_date', models.DateField(verbose_name='Hire date')),
            ],
        ),
    ]
