# Generated by Django 4.2 on 2025-09-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_jobposition_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Title'),
        ),
    ]
